name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  go-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Test with GO test
        run: |
          pushd nebula-docker-compose/
          enable_ssl=false docker-compose up -d
          sleep 10
          popd
          go test -v -race
      - name: Test SSL connection
        run: |
          pushd nebula-docker-compose/
          enable_ssl=true docker-compose up -d
          sleep 10
          popd
          ssl_test=true go test -v -run TestSSLConnection
      - name: Run examples
        run: |
          go run basic_example/graph_client_basic_example.go
          go run gorountines_example/graph_client_goroutines_example.go
        
