name: test
on:
  push:
    branches: [ master, 'release-**']
  pull_request:
    branches: [ master, 'release-**']
  schedule:
    - cron: "0 6 * * *"

jobs:
  go-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: ['1.16', '1.17', '1.18', '1.19', '1.20', '1.21']
    steps:
      - uses: actions/checkout@v2
      - name: Setup go ${{ matrix.goVer }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.goVer }}
      - name: Test with GO test
        run: |
          make up
          sleep 10
          make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      - name: down
        if: always()
        run: |
          make down
  go-client-ssl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: ['1.16', '1.17', '1.18', '1.19', '1.20', '1.21']
    steps:
      - uses: actions/checkout@v2
      - name: Setup go ${{ matrix.goVer }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.goVer }}
      - name: Test SSL connection with CA
        run: |
          make up-ssl
          sleep 10
          make ssl-test
      - name: Test SSL connection self-signed
        run: |
          make up-ssl
          sleep 10
          make ssl-test-self-signed
      - name: down
        if: always()
        run: |
          make down
  go-client-example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: ['1.16', '1.17', '1.18', '1.19', '1.20', '1.21']
    steps:
      - uses: actions/checkout@v2
      - name: Setup go ${{ matrix.goVer }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.goVer }}
      - name: Run examples
        run: |
          make up
          sleep 10
          make run-examples
      - name: down
        if: always()
        run: |
          make down
